### ISSUE TITLE
Broken link in 'Contributed by' inside of Code Snippet 

### ISSUE THREAD

**Issue by Devamchaudhari** [dostonnabotov/quicksnip#21]
There is a broken link in the "Contributed by" inside of Code Snippet . The link is currently leading to a 404 error page of github, and it needs to be updated.

Steps to reproduce:

1. Open the Code Snippet ( eg:  open any code snippet of javascript )
2. Their is a link below Description as a Contributed by [technoph1le](https://github.com/technoph1le)
3. Click on the link it will lead to a 404 error page of github.
4. Expected behavior: The link should point to a valid resource or URL.

![image](https://github.com/user-attachments/assets/d6542106-2e0b-4b09-9f21-3570bfb6a3e9)

**Comment by dostonnabotov** [comment]
Hey, there! It was my different account. I had deleted it, and now I'm able to restore it 90 days later. Was switching from my personal to brand name. :)

**Comment by Devamchaudhari** [comment]
Thank you for the clarification! I completely understand the reason for the account change. Glad to hear it’s all sorted now, and switching to a brand name makes sense for consistency across platforms 🚀.  Then, should I close this issue? 🤔

**Comment by dostonnabotov** [comment]
Sure. There might be more questions related to broken link until I change my account name. 😅 I will link this issue when question rises. Or perhaps I might changed it to my current account, then when the other account is fixed, I will change them back,

**Comment by Devamchaudhari** [comment]
Great idea! If someone asks the same question, please use the issue PR link. Temporarily attaching your own account also works great. When your brand account becomes active again. Both ideas appear to be practical for handling the situation smoothly! 👏👏
