### ISSUE TITLE
framework choice and scalability 

### ISSUE THREAD

**Issue by JaberChowdhury** [dostonnabotov/quicksnip#43]
For future scalability we should use nextjs.
instead of a single javascript.json file we should use a javascript folder then we can use multiple json file for example
* cpp
* css
* python
  * ListManipulation-1.json
  * ListManipulation-2.json
* javascript
  * ArrayManipulation-1.json
  * ArrayManipulation-2.json
  * StringManipulation-1.json
  * StringManipulation-2.json
  * etc.......

**Comment by Mathys-Gasnier** [comment]
The structure seems good currently, it can and will support lot of snippets, there are no really need to switch to nextjs...
Also we already discussed in #16 on how we could improve the current storage/user experience on making snippets.
What comes out of it is a tool to help create snippets, and we keep the current storage, at least for the moment.

The current way of storing snippets isn't the most ideal, but it does it's job great.
