### ISSUE TITLE
[Feature] - Add snippets in markdown instead Json. 

### ISSUE THREAD

**Issue by aumirza** [dostonnabotov/quicksnip#59]
### What feature would you like to see?

While adding code in array it gets hard to manage indentation.

And we can use something like directories and files with markdown.
and properties too for storing metadata and a category json.

Similar to docusaurus setup.

**Comment by Mathys-Gasnier** [comment]
This is already being fixed by #39, we will not change the format used to save snippets, but instead provide tools that makes it easier to create snippets.
