### ISSUE TITLE
Fix "consolidate-snippest" workflow for search functionality

### ISSUE THREAD

**Issue by dostonnabotov** [dostonnabotov/quicksnip#7]
Since we have multiple files, I created a GitHub Action that merges all files within `/public/data` folder (except for `_index.json`) whenever there is a change in that folder and converts them in a single file, called `all_snippests.json` under `/public/consolidated`.

However, converting it correct JSON format is becoming a headache. Tried several alternatives to convert the files in the following format:

```json
[
  { "language": "javascript", "categoryName": "Name of category", "snippets": [] }
]
```

I'm open to ideas to convert them properly.

**Comment by Yugveer06** [comment]
As I see you are currently using bash/jq commands to merge the data files., which might be harder to maintain and less reliable.
How about switching to node for the script?

Something like this?
```js
const fs = require("fs");
const path = require("path");

const dataDir = "public/data";
const outputFile = "public/consolidated/all_snippets.json";

const files = fs.readdirSync(dataDir).filter(f => f.endsWith(".json") && f !== "_index.json");

const consolidated = [];

files.forEach(file => {
	const language = path.basename(file, ".json");
	const content = JSON.parse(fs.readFileSync(path.join(dataDir, file)));

	content.forEach(category => {
		consolidated.push({
			language,
			categoryName: category.categoryName,
			snippets: category.snippets,
		});
	});
});

fs.mkdirSync("public/consolidated", { recursive: true });
fs.writeFileSync(outputFile, JSON.stringify(consolidated, null, 2));
```

and using this script in the github action.

**Comment by dostonnabotov** [comment]
Didn't think about using node. Thanks for the script as well. Will update it.

**Comment by dostonnabotov** [comment]
Switched it to node. And, the issue is fixed. Thanks for the suggestion. 👍

[Commit info](https://github.com/dostonnabotov/quicksnip/commit/648969ac7887931e6c2efc69613131f7c89c6574)
